[package]
name = "rgrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["cargo"] }
features = "0.10.0"
fs = "0.0.5"
prelude = "0.2.1"
rayon = "1.10.0"
regex = "1.11.1"
